// Food on Ways — sample data (all original / generic)
window.FOW_DATA = (function () {
  // Real food imagery — Unsplash URLs. If any fail, the gradient placeholder shows through.
  const IMG = {
    biryani:     "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=900&q=80",
    biryani2:    "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=900&q=80",
    biryani3:    "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=900&q=80",
    crab:        "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=900&q=80",
    seafood:     "https://images.unsplash.com/photo-1535140728325-a4d3707eee94?w=900&q=80",
    fish:        "https://images.unsplash.com/photo-1611599537845-1c7aca0091c0?w=900&q=80",
    fishCurry:   "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=900&q=80",
    coffee:      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80",
    pastry:      "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=900&q=80",
    bun:         "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=80",
    appam:       "https://images.unsplash.com/photo-1630383249896-424e482df921?w=900&q=80",
    stew:        "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=900&q=80",
    dosa:        "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=900&q=80",
    dosa2:       "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=900&q=80",
    curry:       "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&q=80",
    thali:       "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=900&q=80",
    streetNight: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&q=80",
    diningRoom:  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=80",
    backwater:   "https://images.unsplash.com/photo-1582719188393-bb71ca45dbb9?w=900&q=80",
    bananaLeaf:  "https://images.unsplash.com/photo-1604908554027-39fa1bbf60a3?w=900&q=80",
    interior:    "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80",
    cover:       "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900&q=80",
  };

  // Image placeholder palettes — each restaurant/dish gets a tuned warm gradient.
  // No real photos; the visual stub conveys mood + has a monospace tag describing
  // what dish/scene should go there.
  const palettes = {
    saffron: ["#F2A03D", "#C84313", "#6E2B4A"],
    crab:    ["#D9542A", "#7E1F1F", "#2A0F0A"],
    coconut: ["#F5E1B7", "#C8A36C", "#5D3E1F"],
    leaf:    ["#A8B86D", "#465B2B", "#1F2A12"],
    ocean:   ["#74B6B0", "#2A5C66", "#0F2A33"],
    rose:    ["#F4B7A3", "#C56173", "#5E1E2A"],
    char:    ["#9A8470", "#4A372B", "#1A120D"],
    butter:  ["#FFE3B0", "#E2974A", "#7B3A0E"],
    spice:   ["#E55B2D", "#8C2A1A", "#321008"],
    palm:    ["#D9E1B4", "#7A8E45", "#2E3A14"],
    dosa:    ["#F4D69A", "#A06724", "#4E2A0E"],
    night:   ["#3B2A24", "#1A1512", "#0B0807"],
  };

  const restaurants = [
    {
      id: "paragon",
      name: "Paragon",
      cuisines: ["Malabar", "Seafood", "Biryani"],
      area: "Kannur Road",
      city: "Kozhikode",
      distance: "1.2 km",
      hours: "Open · Closes 11pm",
      open: true,
      wishlistedBy: 184,
      since: 1939,
      palette: palettes.crab,
      img: IMG.crab,
      heroTag: "hero · pepper crab on banana leaf",
      flavour: "Feeding Kozhikode since 1939. Come for the Malabar biryani — every grain separate, fragrant with kewra. Leave room for the pathiri.",
      mustOrder: [
        { name: "Malabar Chicken Biryani", note: "Their most wishlisted dish", palette: palettes.saffron, img: IMG.biryani, tag: "dish · biryani plated" },
        { name: "Pepper Crab Roast", note: "The reason people come back", palette: palettes.crab, img: IMG.crab, tag: "dish · crab masala close-up" },
        { name: "Pathiri & Mutton Curry", note: "Soft rice flatbread, deep gravy", palette: palettes.char, img: IMG.curry, tag: "dish · pathiri stack" },
      ],
      photos: [
        { palette: palettes.crab, img: IMG.crab, tag: "hero · pepper crab close-up" },
        { palette: palettes.spice, img: IMG.biryani, tag: "biryani being plated" },
        { palette: palettes.night, img: IMG.diningRoom, tag: "interior · wooden tables" },
        { palette: palettes.coconut, img: IMG.appam, tag: "pathiri stack" },
        { palette: palettes.leaf, img: IMG.bananaLeaf, tag: "banana leaf spread" },
      ],
    },
    {
      id: "sagar",
      name: "Sagar",
      cuisines: ["Coastal", "Seafood"],
      area: "Beach Road",
      city: "Kozhikode",
      distance: "2.4 km",
      hours: "Open · Closes 10:30pm",
      open: true,
      wishlistedBy: 92,
      palette: palettes.ocean,
      img: IMG.fish,
      heroTag: "hero · grilled karimeen on plate",
      flavour: "Beachside coastal cooking that doesn't bother with frills. The karimeen pollichathu arrives wrapped, steaming, and slightly defiant.",
      mustOrder: [
        { name: "Karimeen Pollichathu", note: "Wrapped in banana leaf", palette: palettes.leaf, img: IMG.bananaLeaf, tag: "dish · banana leaf wrap" },
        { name: "Squid Roast", note: "Sea-salt forward", palette: palettes.ocean, img: IMG.seafood, tag: "dish · squid masala" },
      ],
      photos: [
        { palette: palettes.ocean, img: IMG.seafood, tag: "fish on the grill" },
        { palette: palettes.leaf, img: IMG.bananaLeaf, tag: "karimeen wrap" },
        { palette: palettes.palm, img: IMG.backwater, tag: "beachside seating" },
      ],
    },
    {
      id: "kayees",
      name: "Kayees Rahmathulla",
      cuisines: ["Biryani", "Mughlai"],
      area: "Mattancherry",
      city: "Kochi",
      distance: "4.1 km",
      hours: "Open · Closes 9:30pm",
      open: true,
      wishlistedBy: 311,
      palette: palettes.saffron,
      img: IMG.biryani2,
      heroTag: "hero · mutton biryani at counter",
      flavour: "A 75-year-old Mattancherry institution. The biryani is short-grain, fatty, and made in a way that has not been updated, on purpose.",
      mustOrder: [
        { name: "Mutton Biryani", note: "Order before noon or miss it", palette: palettes.saffron, img: IMG.biryani2, tag: "dish · biryani in copper" },
        { name: "Chicken Biryani", note: "Same dough, different soul", palette: palettes.butter, img: IMG.biryani3, tag: "dish · biryani chicken" },
      ],
      photos: [
        { palette: palettes.saffron, img: IMG.biryani2, tag: "biryani being served" },
        { palette: palettes.night, img: IMG.interior, tag: "counter at lunch hour" },
      ],
    },
    {
      id: "topform",
      name: "Topform",
      cuisines: ["Café", "Breakfast"],
      area: "Mavoor Road",
      city: "Kozhikode",
      distance: "0.8 km",
      hours: "Open · Closes 11pm",
      open: true,
      wishlistedBy: 64,
      palette: palettes.butter,
      img: IMG.coffee,
      heroTag: "hero · cappuccino latte art",
      flavour: "Where the city's coffee snobs forgive the design and stay for the slow-pour V60. Best with the cardamom bun.",
      mustOrder: [
        { name: "Cardamom Bun", note: "Sold out by noon", palette: palettes.butter, img: IMG.bun, tag: "dish · cardamom bun" },
        { name: "V60 Pour-over", note: "Single origin rotates weekly", palette: palettes.char, img: IMG.coffee, tag: "dish · pour-over close" },
      ],
      photos: [
        { palette: palettes.butter, img: IMG.pastry, tag: "pastry case" },
        { palette: palettes.char, img: IMG.coffee, tag: "espresso machine" },
      ],
    },
    {
      id: "appammachi",
      name: "Appammachi",
      cuisines: ["Traditional Kerala", "Breakfast"],
      area: "Fort Kochi",
      city: "Kochi",
      distance: "5.6 km",
      hours: "Open · Closes 3pm",
      open: false,
      wishlistedBy: 142,
      palette: palettes.coconut,
      img: IMG.appam,
      heroTag: "hero · lacy appam with stew",
      flavour: "A breakfast-only room run by two sisters. The appam is lacy at the edges and pillow-soft at the centre. Stew is mutton, always.",
      mustOrder: [
        { name: "Appam & Mutton Stew", note: "The reason this place exists", palette: palettes.coconut, img: IMG.appam, tag: "dish · appam + stew" },
        { name: "Idiyappam Set", note: "Side of egg roast", palette: palettes.butter, img: IMG.stew, tag: "dish · idiyappam stack" },
      ],
      photos: [
        { palette: palettes.coconut, img: IMG.appam, tag: "appam being made" },
        { palette: palettes.palm, img: IMG.stew, tag: "sisters at the stove" },
      ],
    },
    {
      id: "thalassery",
      name: "Thalassery Calling",
      cuisines: ["Malabar", "Biryani"],
      area: "MG Road",
      city: "Thrissur",
      distance: "—",
      hours: "Open · Closes 10pm",
      open: true,
      wishlistedBy: 47,
      palette: palettes.spice,
      img: IMG.biryani,
      heroTag: "hero · thalassery biryani plate",
      flavour: "A young Thalassery chef cooking his grandmother's biryani out of a small Thrissur kitchen. Khaima rice. Short list. No menu reform.",
      mustOrder: [
        { name: "Thalassery Biryani", note: "Khaima rice, short-grained", palette: palettes.spice, img: IMG.biryani, tag: "dish · biryani plated" },
      ],
      photos: [{ palette: palettes.spice, img: IMG.biryani, tag: "biryani at the pass" }],
    },
    {
      id: "moplah",
      name: "Moplah Kitchen",
      cuisines: ["Malabar", "Heritage"],
      area: "Kuttichira",
      city: "Kozhikode",
      distance: "3.5 km",
      hours: "Open · Closes 10pm",
      open: true,
      wishlistedBy: 78,
      palette: palettes.rose,
      img: IMG.curry,
      heroTag: "hero · mutton kuzhimanthi rice mound",
      flavour: "Heritage Moplah Muslim cooking from Kuttichira. The Kuzhimanthi — slow-cooked mutton over rice — is the dish people travel for.",
      mustOrder: [
        { name: "Mutton Kuzhimanthi", note: "Eats best with hands", palette: palettes.rose, img: IMG.curry, tag: "dish · kuzhimanthi rice" },
        { name: "Mutta Mala", note: "A wedding dessert", palette: palettes.butter, img: IMG.pastry, tag: "dish · egg-thread dessert" },
      ],
      photos: [{ palette: palettes.rose, img: IMG.curry, tag: "kuzhimanthi served" }],
    },
    {
      id: "dosadosa",
      name: "Dosa Dosa Dosa",
      cuisines: ["South Indian", "Street Food"],
      area: "Palayam",
      city: "Thiruvananthapuram",
      distance: "—",
      hours: "Open · Closes midnight",
      open: true,
      wishlistedBy: 38,
      palette: palettes.dosa,
      img: IMG.dosa,
      heroTag: "hero · giant paper dosa on griddle",
      flavour: "Late-night dosa stall that became a destination. 28 dosa variants. The Mysore Masala is the gateway; the Ghee Roast is the destination.",
      mustOrder: [
        { name: "Mysore Masala Dosa", note: "Spiced red chutney inside", palette: palettes.dosa, img: IMG.dosa, tag: "dish · masala dosa" },
        { name: "Ghee Roast", note: "Crisp, lacy, golden", palette: palettes.butter, img: IMG.dosa2, tag: "dish · ghee roast dosa" },
      ],
      photos: [{ palette: palettes.dosa, img: IMG.dosa, tag: "dosa on griddle" }],
    },
  ];

  const creators = [
    {
      id: "neha",
      name: "Neha Pillai",
      handle: "@nehaeats",
      tier: "Tastemaker",
      city: "Kozhikode",
      bio: "Chasing the best biriyani across Kerala. 4 years, 200 plates in.",
      stats: { posts: 312, saves: 8400, visited: 187 },
      paletteCover: palettes.crab,
      img: IMG.crab,
    },
    {
      id: "arjun",
      name: "Arjun Menon",
      handle: "@arjunbites",
      tier: "Explorer",
      city: "Kochi",
      bio: "Fort Kochi local. Specialty: things grandmothers make.",
      stats: { posts: 142, saves: 3100, visited: 96 },
      paletteCover: palettes.coconut,
      img: IMG.appam,
    },
    {
      id: "sara",
      name: "Sara Iqbal",
      handle: "@saracooks",
      tier: "Tastemaker",
      city: "Kozhikode",
      bio: "Moplah cooking, slow trips, late nights.",
      stats: { posts: 88, saves: 4200, visited: 64 },
      paletteCover: palettes.rose,
      img: IMG.curry,
    },
    {
      id: "ravi",
      name: "Ravi Krishnan",
      handle: "@ravikrishnan",
      tier: "Explorer",
      city: "Thrissur",
      bio: "Filter coffee + spreadsheet kind of guy.",
      stats: { posts: 64, saves: 1800, visited: 41 },
      paletteCover: palettes.char,
      img: IMG.coffee,
    },
    {
      id: "leela",
      name: "Leela Varma",
      handle: "@leelavarma",
      tier: "Editor",
      city: "Alappuzha",
      bio: "Toddy shops, boatmen lunches, backwater finds.",
      stats: { posts: 211, saves: 9600, visited: 142 },
      paletteCover: palettes.palm,
      img: IMG.backwater,
    },
  ];

  const cuisines = [
    { id: "kerala",   label: "Kerala",          palette: palettes.coconut, tag: "appam + stew" },
    { id: "malabar",  label: "Malabar",         palette: palettes.spice,   tag: "biryani close" },
    { id: "seafood",  label: "Seafood",         palette: palettes.ocean,   tag: "fish on plate" },
    { id: "street",   label: "Street Food",     palette: palettes.dosa,    tag: "street dosa" },
    { id: "fine",     label: "Fine Dining",     palette: palettes.night,   tag: "plated tasting" },
    { id: "biryani",  label: "Biryani Trails",  palette: palettes.saffron, tag: "biryani plated" },
    { id: "south",    label: "South Indian",    palette: palettes.butter,  tag: "thali brass" },
    { id: "coastal",  label: "Coastal",         palette: palettes.palm,    tag: "coastal spread" },
    { id: "thali",    label: "Thaali",          palette: palettes.leaf,    tag: "leaf meal" },
    { id: "fusion",   label: "Fusion",          palette: palettes.rose,    tag: "fusion plate" },
    { id: "cafe",     label: "Café Culture",    palette: palettes.char,    tag: "latte" },
    { id: "dessert",  label: "Desserts",        palette: palettes.butter,  tag: "payasam bowl" },
  ];

  const events = [
    {
      id: "heritage-walk",
      name: "Kozhikode Heritage Food Walk",
      date: "Sat, May 24",
      time: "6:30pm",
      venue: "Kuttichira to SM Street",
      host: "sara",
      attending: 27,
      spotsLeft: 8,
      price: "₹1,800",
      palette: palettes.spice,
      img: IMG.streetNight,
      tag: "lantern-lit street walk",
    },
    {
      id: "paragon-table",
      name: "Chef's Table at Paragon",
      date: "Fri, May 30",
      time: "8:00pm",
      venue: "Paragon · Kozhikode",
      host: "neha",
      attending: 14,
      spotsLeft: 2,
      price: "₹3,500",
      palette: palettes.crab,
      img: IMG.diningRoom,
      tag: "private dining room",
    },
    {
      id: "backwater-lunch",
      name: "Backwater Toddy & Lunch",
      date: "Sun, Jun 2",
      time: "12:30pm",
      venue: "Alappuzha",
      host: "leela",
      attending: 9,
      spotsLeft: 4,
      price: "₹2,400",
      palette: palettes.palm,
      img: IMG.backwater,
      tag: "houseboat lunch" ,
    },
  ];

  // Creator posts in the feed
  const posts = [
    {
      id: "p1",
      creator: "neha",
      timeAgo: "2h",
      restaurantId: "paragon",
      mediaPalette: palettes.crab,
      mediaImg: IMG.crab,
      mediaTag: "post · pepper crab on banana leaf",
      caption: "Came for the biryani. Stayed two hours longer because of the pepper crab. Order both. Skip the bread.",
      saves: 412,
    },
    {
      id: "p2",
      creator: "arjun",
      timeAgo: "5h",
      restaurantId: "appammachi",
      mediaPalette: palettes.coconut,
      mediaImg: IMG.appam,
      mediaTag: "post · appam lacy edges",
      caption: "Two sisters. One pan. The appam has actual lace at the edge — like someone embroidered it.",
      saves: 287,
    },
    {
      id: "p3",
      creator: "sara",
      timeAgo: "1d",
      restaurantId: "moplah",
      mediaPalette: palettes.rose,
      mediaImg: IMG.curry,
      mediaTag: "post · kuzhimanthi rice mound",
      caption: "Moplah Kitchen makes Kuzhimanthi the way my Umma did. I'm not sure I'll eat it anywhere else now.",
      saves: 524,
    },
    {
      id: "p4",
      creator: "ravi",
      timeAgo: "2d",
      restaurantId: "topform",
      mediaPalette: palettes.butter,
      mediaImg: IMG.bun,
      mediaTag: "post · cardamom bun close-up",
      caption: "The cardamom bun at Topform is not negotiable. Get there before 11.",
      saves: 156,
    },
  ];

  return { palettes, restaurants, creators, cuisines, events, posts, IMG };
})();
